"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.COMPRESSED_MESSAGE = exports.SERVER_TIME = exports.GENERATE_KEYS = exports.PING_PONG = exports.OUTDATED_CLIENT_ERROR = exports.SPECTATE_MODE_IS_FULL = exports.SERVER_DEATH = exports.TOKEN_ACCEPTED = exports.MOBILE_DATA = exports.RECAPTCHA_V3 = exports.RECAPTCHA_V2 = exports.GHOST_CELLS = exports.LEADERBOARD2 = exports.LEADERBOARD = exports.ADD_OWN_CELL = exports.FLUSH = exports.VIEWPORT_UPDATE = exports.SOCKET_CLOSED = exports.SOCKET_CLOSING = exports.SOCKET_OPENED = exports.SOCKET_CONNECTING = void 0;
exports.SOCKET_CONNECTING = 0;
exports.SOCKET_OPENED = 1;
exports.SOCKET_CLOSING = 2;
exports.SOCKET_CLOSED = 3;
exports.VIEWPORT_UPDATE = 17;
exports.FLUSH = 18;
exports.ADD_OWN_CELL = 32;
exports.LEADERBOARD = 53;
exports.LEADERBOARD2 = 54;
exports.GHOST_CELLS = 69;
exports.RECAPTCHA_V2 = 85;
exports.RECAPTCHA_V3 = 87;
exports.MOBILE_DATA = 102;
exports.TOKEN_ACCEPTED = 103;
exports.SERVER_DEATH = 113;
exports.SPECTATE_MODE_IS_FULL = 114;
exports.OUTDATED_CLIENT_ERROR = 128;
exports.PING_PONG = 226;
exports.GENERATE_KEYS = 241;
exports.SERVER_TIME = 242;
exports.COMPRESSED_MESSAGE = 255;
