"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SOCKET_CONNECTION_REJECT = void 0;
var SOCKET_CONNECTION_REJECT;
(function (SOCKET_CONNECTION_REJECT) {
    SOCKET_CONNECTION_REJECT["NO_RESPONSE_FROM_SERVER"] = "NO_RESPONSE_FROM_SERVER";
    SOCKET_CONNECTION_REJECT["NO_HANDSHAKE"] = "NO_HANDSHAKE";
})(SOCKET_CONNECTION_REJECT = exports.SOCKET_CONNECTION_REJECT || (exports.SOCKET_CONNECTION_REJECT = {}));
